version: 0.2
phases:
  install:
    commands:
      - apt-get update && apt install -y --no-install-recommends nginx curl
  pre_build:
    commands:
      - service nginx start
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go build ./lab_01/hello.go
  post_build:
    commands:
      - ls /var
      - ps -ef
      - curl localhost
      - cat /etc/nginx/nginx.conf
      - ./lab_01/hello.go >> /var/www/html/index.html
artifacts:
  files:
    - '**/*'
  base-directory: lab_01
  discard-paths: yes
