version: 0.2
phases:
  install:
    commands:
      - apt-get update && apt install -y --no-install-recommends apache2 curl
  pre_build:
    commands:
      - service apache2 start
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go build ./lab_01/hello.go
  post_build:
    commands:
      - ps -ef
      - curl localhost
      - ./hello >> /var/www/html/index.html
      - TIME=date && echo 'time of build $TIME' > /var/www/html/index2.html
      - curl localhost/index.html
      - curl localhost/index2.html
artifacts:
  files:
    - '/var/www/html/index2.html'
  base-directory: lab_01
  discard-paths: yes
